apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: springapp
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: royalespn/prometheussimple:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
