global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: redis-exporter
    static_configs:
      - targets: ['host.docker.internal:9121']

  - job_name: RabbitMQ
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:15692']

  - job_name: SpringBoot-application
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: Pushgateway
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:9091']

rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093